# Generated by Django 5.1.1 on 2024-09-30 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promanagement", "0005_alter_post_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
    ]
