# Generated by Django 5.1.1 on 2024-09-30 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promanagement", "0006_userprofile_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="total_dislikes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="post",
            name="total_likes",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
